### ISSUE TITLE
Bug MasterOut

### ISSUE THREAD

**Issue by verygood142** [marpe/XnaDarts#7]
I recommend if you can add the master In and tips on how to finish. For example, if you are on 155, would
say "T20 T19 D19" in the top of the screen?

**Comment by marpe** [comment]
I uploaded a new release which hopefully fixes the master out issue, but I have not tested it a lot. Will start working on the tips on how to finish once the master out feature has been further tested.

**Comment by verygood142** [comment]
It tested several times and is the bug fixed. it works perfectly :-)

Adviser to add Master In and tips on how to finish, example T20 T19 D19" in the top of the screen

**Comment by marpe** [comment]
Nice, then I'll close this issue and start working on the tips on how to finish
